language: python

python:
  - "2.7"
  - "3.5"

env:
  - TOXENV=django16
  - TOXENV=django19
  - TOXENV=django111

install:
  - pip install tox

before_script:
  - psql -U postgres -c "create database django encoding 'UTF8'"

script: tox -e $TOXENV
